build: creating a Dockerfile, application example
IntrinsicLabs/osgood pull request #32
Opened 2019-08-08 19:37 UTC by tlhunter

This adds an example `Dockerfile` which can be used to build a base image:

```shell
$ docker build -t osgood .
```

Once that's done an application can then create their own `Dockerfile` to extend `osgood`:

```Dockerfile
FROM osgood
COPY ./*.js /srv/osgood/
EXPOSE 8080
CMD ["app.js"]
```

And run their own app via:

```bash
$ cd examples/simple
$ docker build -t osgood-simple-app .
$ docker run -p 8080:8080 osgood-simple-app
```

We should consider putting the base image on Docker Hub. We should tag each image using the same underlying Osgood version number (e.g. `NAMESPACE/osgood:0.2.1`).

2019-08-08 19:38 UTC, tlhunter commented on Dockerfile
> +	apt-get upgrade -y; \
I think this can be omitted; I believe the base `ubuntu` image is constantly updated with newer packages.

2019-08-08 19:39 UTC, tlhunter commented on Dockerfile
> +
TODO: The script should verify the ZIP file download SHA hash before continuing. This is common practice, see:

https://github.com/docker-library/redis/blob/3193aad4ff9f2ea482a57d4a296b6541237f682c/5.0/Dockerfile#L43-L44

2019-08-08 21:11 UTC, bengl requested changes

2019-08-08 21:11 UTC, bengl commented on Dockerfile
> +FROM ubuntu:xenial
do we have any chance at using a smaller base image?

2019-08-08 21:20 UTC, talbenari1 requested changes

2019-08-08 21:20 UTC, talbenari1 commented on Dockerfile
> +RUN set -eux; \
Why `;` instead of `&&`? Don't we want the build to stop if any of these steps fail?

2019-08-08 21:20 UTC, talbenari1 commented on examples/simple/app.js
>  // app.interface = '0.0.0.0'; -- default so commented it out
Can you either remove the "default so commented it out" or add it to the other line?

2019-08-08 21:33 UTC, tlhunter commented on Dockerfile
> +FROM ubuntu:xenial
It was the oldest distro I could find which still receives security updates and supports our old version of SSL. The following OSs don't work, for example:

```Dockerfile
FROM ubuntu:bionic
FROM debian:jessie
FROM debian:stretch-slim
FROM debian:buster-slim
```

If possible we should configure CI to use bionic, then I think I can get it working with the modern Debian 10 "buster" release.

2019-08-08 21:45 UTC, tlhunter commented on Dockerfile
> +FROM ubuntu:xenial
Looks like we can update `.travis.yml` by adding this line:

```yaml
dist: xenial
```

However any builds resulting from this will probably link against the more modern SSL library and wouldn't run on the same machines, making such a change a MAJOR.

2019-08-08 21:52 UTC, tlhunter commented on Dockerfile
> +RUN set -eux; \
It does exit when one of the steps fail due to the `set -e`. This is the most common pattern I've found in `Dockerfile`s, but people do seem to do everything:

- https://github.com/docker-library/redis/blob/3193aad4ff9f2ea482a57d4a296b6541237f682c/5.0/Dockerfile#L9
- https://github.com/docker-library/postgres/blob/db452338a99764f0141aae60f7267a58f665e6b7/9.6/Dockerfile#L54
- https://github.com/nodejs/docker-node/blob/8b960335a3a40954a5e4fe324e3269515367ec65/Dockerfile-debian.template#L19

2019-08-08 21:53 UTC, tlhunter commented on examples/simple/app.js
>  // app.interface = '0.0.0.0'; -- default so commented it out
removed the comments

2019-08-09 21:48 UTC, bengl approved these changes

2019-08-09 21:54 UTC, talbenari1 approved these changes

2019-08-09 21:55 UTC, merged